
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name:     "main"
    arch:     "amd64"
    system:   "linux,darwin"
    mod:      "none"
    packSrc:  "resource,manifest"
#    version:  "v1.0.0"
    output:   "./bin"
    extra:    ""
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - registry.cn-shenzhen.aliyuncs.com/heiku
  gen:
    dao:
      - link:     "mysql:unib:hn02le34lkdLKD@tcp(***REMOVED***:13306)/test?loc=Local&parseTime=true"
        tables:   "test"
        group: "xin"
        daoPath:  "dao/xin"
        doPath:  "model/do/xin"
        entityPath:  "model/entity/xin"
#        jsonCase: "CamelLower"

      - link:   "mysql:unib:hn02le34lkdLKD@tcp(***REMOVED***:13306)/unib?loc=Local&parseTime=true"
#        path:   "oversea_pay"
#        prefix: "primary_"
        group: "oversea_pay"
        daoPath:  "dao/oversea_pay"
        doPath:  "model/do/oversea_pay"
        entityPath:  "model/entity/oversea_pay"
        tables: ""